CREATE TABLE [Invite]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Email nvarchar(128) NOT NULL,
	HouseholdId INT NOT NULL,
	SenderId INT NOT NULL,

	CONSTRAINT FK_INVITE_MEMEBER FOREIGN KEY (SenderId) REFERENCES [User](Id),
	CONSTRAINT FK_INVITE_HOUSEHOLD FOREIGN KEY (HouseholdId) REFERENCES [Household](Id)
)
